FROM golang:1.9-alpine
LABEL maintainer "UshioShugo<ushio.s@gmail.com>"

ENV APP_PATH=${GOPATH}/src/github.com/ushios/docker-swarm-networks

COPY . ${APP_PATH}
WORKDIR ${APP_PATH}

RUN apk update
RUN apk add --no-cache --virtual .goget && \
	go get -v -t ./... && \
	apk del .goget
RUN go build ./server/main.go
